#pragma once

#include "include/AdditionalExpressionParam.hpp"
#include "include/AdditionalExpressionParamS.hpp"
#include "include/AdditionalParam.hpp"
#include "include/AdditionalParamS.hpp"
#include "include/ArrayAssignmentStatement.hpp"
#include "include/CurlyBraceStatement.hpp"
#include "include/DotExpression.hpp"
#include "include/ExpressionParamS.hpp"
#include "include/FalseExpression.hpp"
#include "include/Goal.hpp"
#include "include/IdentifierExpression.hpp"
#include "include/IfElseStatement.hpp"
#include "include/IntliteralExpression.hpp"
#include "include/LengthExpression.hpp"
#include "include/NewArrayExpression.hpp"
#include "include/NewIdentifierExpression.hpp"
#include "include/NotExpression.hpp"
#include "include/Params.hpp"
#include "include/Param.hpp"
#include "include/ParensExpression.hpp"
#include "include/PrintlnStatement.hpp"
#include "include/SquarebracketsExpression.hpp"
#include "include/StatementS.hpp"
#include "include/ThisExpression.hpp"
#include "include/TrueExpression.hpp"
#include "include/VarAssignmentStatement.hpp"
#include "include/WhileStatement.hpp"
#include "include/ClassDeclaration.hpp"
#include "include/MainClass.hpp"
#include "include/ClassDeclarationS.hpp"
#include "include/Extension.hpp"
#include "include/VarDeclarationS.hpp"
#include "include/VarDeclaration.hpp"
#include "include/MethodDeclarationS.hpp"
#include "include/MethodDeclaration.hpp"
#include "include/BinaryOpExpression.hpp"

#include "include/ClassDeclarationList.hpp"
#include "include/VarDeclarationList.hpp"
#include "include/ParamList.hpp"
#include "include/MethodDeclarationList.hpp"
#include "include/StatementList.hpp"
#include "include/ExpressionParamList.hpp"
#include "include/Type.hpp"


