#ifndef COMPILERAST_IADDITTIONALEXPRESSIONPARAMS_H
#define COMPILERAST_IADDITTIONALEXPRESSIONPARAMS_H

#include "IAcceptable.h"

class IAdditionalExpressionParamS : public IAcceptable {

};

#endif //COMPILERAST_IADDITTIONALEXPRESSIONPARAMS_H
