#ifndef COMPILERAST_IADDITTIONALEXPRESSIONPARAM_H
#define COMPILERAST_IADDITTIONALEXPRESSIONPARAM_H

#include "IAcceptable.h"

class IAdditionalExpressionParam : public IAcceptable {

};

#endif //COMPILERAST_IADDITTIONALEXPRESSIONPARAM_H
