#ifndef COMPILERAST_IADDITTIONALEXPRESSIONPARAMS_H
#define COMPILERAST_IADDITTIONALEXPRESSIONPARAMS_H

#include "IAcceptable.h"

class IAddittionalExpressionParamS : public IAcceptable {

};

#endif //COMPILERAST_IADDITTIONALEXPRESSIONPARAMS_H
