#ifndef COMPILERAST_IVISITOR_H
#define COMPILERAST_IVISITOR_H

class CAdditionalExpressionParam;
class CAdditionalExpressionParamS;
class CAdditionalParam;
class CAdditionalParamS;
class CAndExpression;
class CArrayAssignmentStatement;
class CBooleanType;
class CCurlyBraceStatement;
class CCustomType;
class CDotExpression;
class CExpressionParamS;
class CFalseExpression;
class CGoal;
class CIdentifierExpression;
class CIfElseStatement;
class CIntArrayType;
class CIntliteralExpression;
class CIntType;
class CLengthExpression;
class CLessExpression;
class CMinusExpression;
class CMultiplyExpression;
class CNewArrayExpression;
class CNewIdentifierExpression;
class CNotExpression;
class CParams;
class CParensExpression;
class CPlusExpression;
class CPrintlnStatement;
class CSquarebracketsExpression;
class CStatementS;
class CTerminalIdentifier;
class CTerminalIntliteral;
class CThisExpression;
class CTrueExpression;
class CVarAssignmentStatement;
class CWhileStatement;
class CClassDeclaration;
class CMainClass;
class CClassDeclarationS;
class CExtension;
class CVarDeclarationS;
class CVarDeclaration;
class CMethodDeclarationS;
class CMethodDeclaration;

class IAcceptable;

class IVisitor {
public:
    virtual void Visit( const CAdditionalExpressionParam* acceptable ) = 0;
    virtual void Visit( const CAdditionalExpressionParamS* acceptable ) = 0;
    virtual void Visit( const CAdditionalParam* acceptable ) = 0;
    virtual void Visit( const CAdditionalParamS* acceptable ) = 0;
    virtual void Visit( const CAndExpression* acceptable ) = 0;
    virtual void Visit( const CArrayAssignmentStatement* acceptable ) = 0;
    virtual void Visit( const CBooleanType* acceptable ) = 0;
    virtual void Visit( const CClassDeclaration* acceptable ) = 0;
    virtual void Visit( const CClassDeclarationS* acceptable ) = 0;
    virtual void Visit( const CCurlyBraceStatement* acceptable ) = 0;
    virtual void Visit( const CCustomType* acceptable ) = 0;
    virtual void Visit( const CDotExpression* acceptable ) = 0;
    virtual void Visit( const CExpressionParamS* acceptable ) = 0;
    virtual void Visit( const CExtension* acceptable ) = 0;
    virtual void Visit( const CFalseExpression* acceptable ) = 0;
    virtual void Visit( const CGoal* acceptable ) = 0;
    virtual void Visit( const CIdentifierExpression* acceptable ) = 0;
    virtual void Visit( const CIfElseStatement* acceptable ) = 0;
    virtual void Visit( const CIntArrayType* acceptable ) = 0;
    virtual void Visit( const CIntliteralExpression* acceptable ) = 0;
    virtual void Visit( const CIntType* acceptable ) = 0;
    virtual void Visit( const CLengthExpression* acceptable ) = 0;
    virtual void Visit( const CLessExpression* acceptable ) = 0;
    virtual void Visit( const CMainClass* acceptable ) = 0;
    virtual void Visit( const CMethodDeclaration* acceptable ) = 0;
    virtual void Visit( const CMethodDeclarationS* acceptable ) = 0;
    virtual void Visit( const CMinusExpression* acceptable ) = 0;
    virtual void Visit( const CMultiplyExpression* acceptable ) = 0;
    virtual void Visit( const CNewArrayExpression* acceptable ) = 0;
    virtual void Visit( const CNewIdentifierExpression* acceptable ) = 0;
    virtual void Visit( const CNotExpression* acceptable ) = 0;
    virtual void Visit( const CParams* acceptable ) = 0;
    virtual void Visit( const CParensExpression* acceptable ) = 0;
    virtual void Visit( const CPlusExpression* acceptable ) = 0;
    virtual void Visit( const CPrintlnStatement* acceptable ) = 0;
    virtual void Visit( const CSquarebracketsExpression* acceptable ) = 0;
    virtual void Visit( const CStatementS* acceptable ) = 0;
    virtual void Visit( const CTerminalIdentifier* acceptable ) = 0;
    virtual void Visit( const CTerminalIntliteral* acceptable ) = 0;
    virtual void Visit( const CThisExpression* acceptable ) = 0;
    virtual void Visit( const CTrueExpression* acceptable ) = 0;
    virtual void Visit( const CVarAssignmentStatement* acceptable ) = 0;
    virtual void Visit( const CVarDeclaration* acceptable ) = 0;
    virtual void Visit( const CVarDeclarationS* acceptable ) = 0;
    virtual void Visit( const CWhileStatement* acceptable ) = 0;
};

#endif